- name: Increase Storage for User (Create text file)

  hosts: jailhost

  gather_facts: no
    
  vars:
    ansible_user: ansible

    undefined_variables: []

    request_amount: "{{ amount | float}}"

    request_unit: "gb"

    request_action: "{{ 'increase' if (verbs_positive|bool == True) else 'decrease'}}"

    request_net_change: "{{ request_amount if request_action == 'increase' else request_amount * -1 }}"

    current_quota: '{{ (ansible_zfs_datasets[0].reservation | replace("G", "")) | float}}'

    increase_amount: '{{(current_quota|float + request_net_change|float) if modifiers == "by" else request_amount|float }}'

  vars_files:
    - ../vars/shared_vars.yaml

  tasks:
    - name: "Send email notifying of invalid request"
      community.general.mail:
              host: '{{ mail_server }}'
              port: '{{ mail_port }}'
              secure: always
              username: '{{ helpdesk_email }}'
              password: '{{ helpdesk_password }}'
              to: '{{ from }}'
              from: '{{ helpdesk_email }}'
              subject: "Could not execute your recent user management request"
              body: "We couldn't understand what you wanted from your previous user management request. Please ensure that all necessary information is included. Send an email with the subject: Help and body: 'help with: manage_users' to see how to properly format your request.'"
      when: verbs_positive == None and verbs_negative == None and queries == None

    - name: "Exit playbook run if invalid request"
      ansible.builtin.fail:
        msg: "Invalid request"
      when: verbs_positive == None and verbs_negative == None and queries == None

    - name: User Storage Query
      community.general.zfs_facts:
        dataset: 'zroot/empt/homes/{{ targets }}'
      register: zfs_query
      ignore_errors: true

    - name: "Send email notifying if target username is undefined"
      community.general.mail:
        host: '{{ mail_server }}'
        port: '{{ mail_port }}'
        secure: always
        username: '{{ helpdesk_email }}'
        password: '{{ helpdesk_password }}'
        to: '{{ from }}'
        from: '{{ helpdesk_email }}'
        subject: "Could not execute your recent user management request"
        body: "The username provided: {{ targets }} is not a valid user. Please ensure to include a user with the format 'username: targeted_username', and that the user exists in your organization."
      when: targets == None or zfs_query is failed

    - name: "Exit playbook run if no username is provided"
      ansible.builtin.fail:
        msg: "A username was not provided in the email request"
      when: targets == None or zfs_query is failed
  
    - name: Increase/Decrease Storage section
      block:
        - name: Increase user storage
          ansible.builtin.command: 'zfs set reservation={{ increase_amount }}G zroot/empt/homes/{{ targets }}' # ask about this
          remote_user: ansible
          become: true
          become_method: community.general.doas
          register: zfs_increase_storage_output
          ignore_errors: true

        - name: "Send failure message if zfs failed"
          community.general.mail:
            host: '{{ mail_server }}'
            port: '{{ mail_port }}'
            secure: always
            username: '{{ helpdesk_email }}'
            password: '{{ helpdesk_password }}'
            to: '{{ [ targets ,  from ] | unique }}'
            from: '{{ helpdesk_email }}'
            subject: "Failed to increase storage allocation"
            body: "Your storage increase request failed for the following reason: {{ zfs_increase_storage_output.stderr }}. Please contact your IT department and provide them with this error, if it is not easily fixable."
          when: zfs_increase_storage_output.rc != 0
        
        - name: Send confirmation Email
          community.general.mail:
            host: '{{ mail_server }}'
            port: '{{ mail_port }}'
            secure: always
            username: '{{ helpdesk_email }}'
            password: '{{ helpdesk_password }}'
            to: '{{ [ targets ,  from ] | unique }}'
            from: '{{ helpdesk_email }}'
            subject: "Confirmation of {{ request_action }} storage request for user {{ targets }}"
            body: "The storage quota for user {{ targets }}has been {{request_action}}d {{ modifiers }} {{ request_amount }} {{ request_unit }}"
          when: zfs_increase_storage_output.rc == 0
      when: not queries

    - name: Send query response
      community.general.mail:
        host: '{{ mail_server }}'
        port: '{{ mail_port }}'
        secure: always
        username: '{{ helpdesk_email }}'
        password: '{{ helpdesk_password }}'
        to: '{{ [ targets ,  from ] | unique }}'
        from: '{{ helpdesk_email }}'
        subject: "Storage query for user {{ targets }}"
        body: "Your account has a quota (maximum space) of {{ ansible_zfs_datasets[0].quota }}, of which {{ ansible_zfs_datasets[0].reservation }} is already reserved. You have used {{ ansible_zfs_datasets[0].used }} so far."
      when: queries 
