- name: Create and delete users in the system

  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vars/it_helpdesk_config.yaml
  tasks:
    - name: "Manage Users Help Email"
      community.general.mail:
            host: smtp.gmail.com
            port: 465
            secure: always
            username: '{{ helpdesk_email }}'
            password: '{{ helpdesk_password }}'
            to: 'arnavsajith04@gmail.com'
            from: '{{ helpdesk_email }}'
            subject: "Help with your manage_users request"
            body: "{{ lookup('file', '{{ helpdesk_dir }}/ansible/help_exemplars/manage_users_help.txt') }}" # NEED TO CHANGE THIS TO TEXT FILE
