- name: Email value of requested windows shell script
  hosts: windows_desktop
  vars:
    command: '{{ body }}'
    email: '{{ from }}'

  tasks:
    - name: Run shell
      ansible.windows.win_command: '{{ command }}'
      register: out

    - name: Send reply
      community.general.mail:
        host: smtp.gmail.com
        port: 465
        secure: always
        username: vanrahtijas@gmail.com
        password: xlyvfrrpqbmlrndr
        to: '{{ email }}'
        from: vanrahtijas@gmail.com
        subject: "Here is the result of your command '{{ command }}'"
        body: "{{ out.stdout_lines }}"
      delegate_to: localhost
