- name: Increase Storage for User (Create text file)

  hosts: windows_desktop

  vars:

    request_modifier: "{{ modifier }}"

    request_amount: "{{ amount }}"

    request_unit: "{{ unit }}"

    request_target: "{{ target }}"

    request_action: "{{ 'increase' if (positive_action|bool == True) else 'decrease'}}"

    request_date: "{{ date }}"

    request_from: "{{ from }}"

    destination: C:\Users\{{ ansible_user }}\Documents

  tasks:
    # - name: Navigate to directory
    #   ansible.windows.win_shell: |
    #     cd {{ destination }}
    #     mkdir storage_requests


    - name: Create file
      ansible.windows.win_copy:
        content: Please {{ request_action }} the storage quota for user {{ request_target }} {{ request_modifier }} {{ request_amount }} {{ request_unit }}
        dest: '{{destination}}\storage_requests\storage_request_{{ date }}.txt'
      register: result

    - name: Print out
      ansible.builtin.debug:
        msg: '{{ result }}'
    - name: Send confirmation Email
      community.general.mail:
        host: smtp.gmail.com
        port: 465
        secure: always
        username: vanrahtijas@gmail.com
        # trunk-ignore(checkov/CKV_SECRET_6)
        password: 
        to: '{{ [ request_target ,  request_from ] | unique }}'

        from: vanrahtijas@gmail.com
        subject: "Confirmation of {{ request_action }} storage request for user {{ request_target }}"
        body: "The storage quota for user {{ request_target }} has been {{request_action}}ed {{ request_modifier }} {{ request_amount }} {{ request_unit }}"
      delegate_to: localhost
