- hosts: jailhost
  vars:
      ansible_user: arnav
      request_amount: '{{ amount | float }}'
      current_quota: '{{ (ansible_zfs_datasets[0].quota | replace("G", "")) | float}}'
      increase_amount: '{{(current_quota|float + request_amount|float) if request_modifier == "by" else request_amount|float }}'
  tasks:
    - name: User Storage Query
      community.general.zfs_facts:
        dataset: 'zroot/empt/homes/arnavsajith'
      
      register: output
    - debug:
        msg: 'net change is {{ increase_amount }}'
